apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-project-test-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8-project-test
      version: 1.0.0
  template:
    metadata:
      labels:
        app: k8-project-test
        version: 1.0.0
    spec:
      containers:
        - name: k8-project-test
          image: k8-project-test:1.0.0
          env:
            - name: APP_VERSION
              value: 1.0.0
          ports:
            - name: http
              containerPort: 8080
            - name: multicast
              containerPort: 5701
---
apiVersion: v1
kind: Service
metadata:
  name: k8-project-test-v1
spec:
  selector:
    app: k8-project-test
    version: 1.0.0
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
